# Generated by Django 5.0 on 2023-12-31 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyname', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('district', models.CharField(blank=True, max_length=300, null=True)),
                ('taluka', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('jobname', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyreq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formapp.company')),
            ],
        ),
    ]
