# Generated by Django 5.0 on 2024-01-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_posts_companyreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
