# Generated by Django 5.0 on 2024-01-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_usercompany_userposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='companyreq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.usercompany'),
        ),
    ]
