# Generated by Django 5.0 on 2024-01-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_userposts_companynew_alter_userposts_companyreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='companynew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.company'),
        ),
    ]
